// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc319.SteamworksBob319;

import org.usfirst.frc319.SteamworksBob319.commands.*;
import org.usfirst.frc319.SteamworksBob319.commands.DriveTrain.FollowTrajectory;
//import org.usfirst.frc319.SteamworksBob319.commands.DriveTrain.FollowBothMotionProfiles;
import org.usfirst.frc319.SteamworksBob319.commands.DriveTrain.JoystickDrive;
import org.usfirst.frc319.SteamworksBob319.commands.DriveTrain.ShiftToggle;
import org.usfirst.frc319.SteamworksBob319.commands.FuelCollector.FuelCollectorDeploy;
import org.usfirst.frc319.SteamworksBob319.commands.FuelCollector.FuelCollectorIn;
import org.usfirst.frc319.SteamworksBob319.commands.FuelCollector.FuelCollectorRetract;
import org.usfirst.frc319.SteamworksBob319.commands.FuelCollector.FuelCollectorStop;
import org.usfirst.frc319.SteamworksBob319.commands.GearCollector.AutomatedCollectGearAndLift;
import org.usfirst.frc319.SteamworksBob319.commands.GearCollector.GearCollectorArmDeploy;
import org.usfirst.frc319.SteamworksBob319.commands.GearCollector.GearCollectorArmGoToDepositGear;
import org.usfirst.frc319.SteamworksBob319.commands.GearCollector.GearCollectorIn;
import org.usfirst.frc319.SteamworksBob319.commands.GearCollector.GearCollectorOut;
import org.usfirst.frc319.SteamworksBob319.commands.GearCollector.GearCollectorArmRetract;
import org.usfirst.frc319.SteamworksBob319.commands.GearCollector.GearCollectorStop;
import org.usfirst.frc319.SteamworksBob319.commands.GearCollector.LightsOff;
import org.usfirst.frc319.SteamworksBob319.commands.GearCollector.LightsOn;
import org.usfirst.frc319.SteamworksBob319.commands.Rollervator.AutomatedRollervatorClimb;
import org.usfirst.frc319.SteamworksBob319.commands.Rollervator.RollervatorClimb;
import org.usfirst.frc319.SteamworksBob319.commands.Rollervator.RollervatorGo;
import org.usfirst.frc319.SteamworksBob319.commands.Rollervator.RollervatorStop;
import org.usfirst.frc319.SteamworksBob319.commands.Shooter.ShooterGoToSpeed;
import org.usfirst.frc319.SteamworksBob319.commands.Shooter.ShooterStop;

import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.buttons.*;
import org.usfirst.frc319.SteamworksBob319.subsystems.*;

/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {

	public BobController driverController;
	public BobController operatorController;

	public OI() {

		driverController = new BobController(0);
		operatorController = new BobController(1);
		

		// --------OPERATOR---------------//

		//operatorController.selectButton.whenPressed(new BlueHopperAuto());
		//operatorController.leftBumper.whenPressed(new FollowTrajectory("RedHopperAutoPt1"));
		//operatorController.leftBumper.whenPressed(new LightsOn());
		//operatorController.leftBumper.whenPressed(new FuelCollectorDeploy());
		
		//operatorController.rightBumper.whenPressed(new BlueHopperAuto());
		operatorController.rightBumper.whenPressed(new GearCollectorStop());
		//operatorController.rightBumper.whenPressed(new FollowTrajectory("RedHopperAutoPt2"));
		//operatorController.rightBumper.whenPressed(new FuelCollectorRetract());
		
		
		//operatorController.yButton.whenPressed(new GearCollectorArmGoToDepositGear());
		
		operatorController.aButton.whenPressed(new AutomatedCollectGearAndLift()); // was gearCollectorIn
		//operatorController.aButton.whenPressed(new GearCollectorOut());
		
		
		operatorController.bButton.whenPressed(new FuelCollectorRetract());
		//operatorController.bButton.whenPressed(new GearCollectorOut());
		operatorController.xButton.whenPressed(new FuelCollectorDeploy());
		
		
		
		//operatorController.startButton.whenPressed(new GearCollectorRetract());
		
		
		
		operatorController.selectButton.whenPressed(new AutomatedRollervatorClimb());
		operatorController.startButton.whenPressed(new RollervatorStop());
		
			// -----------DRIVER-----------//

		driverController.leftBumper.whenPressed(new FuelCollectorIn());
		//driverController.leftBumper.whenPressed(new FuelCollectorDeploy());
		driverController.yButton.whenPressed(new ShooterRollervatorStop());
		driverController.xButton.whenPressed(new ShiftToggle());
		driverController.bButton.whenPressed(new RollervatorGo());
		driverController.aButton.whenPressed(new ShooterGoToSpeed());
		driverController.rightBumper.whenPressed(new FuelCollectorStop());
		driverController.startButton.whenPressed(new ShooterStop()); // was BrakePadDeploy
		driverController.selectButton.whenPressed(new RollervatorStop()); // was BrakePadRetract
		//driverController.selectButton.whenPressed(new FuelCollectorRetract());

		/*
		 * // SmartDashboard Buttons SmartDashboard.putData("FuelCollectorGo",
		 * new FuelCollectorGo()); SmartDashboard.putData("AutonomousCommand",
		 * new AutonomousCommand()); SmartDashboard.putData("JoystickDrive", new
		 * JoystickDrive()); SmartDashboard.putData("FuelCollectorStop", new
		 * FuelCollectorStop()); SmartDashboard.putData("GearCollectorGo", new
		 * GearCollectorGo()); SmartDashboard.putData("GearCollectorStop", new
		 * GearCollectorStop()); SmartDashboard.putData("CommandGroup1", new
		 * CommandGroup1());
		 */

	}

	public Joystick getdriverController() {
		return driverController;
	}

	public Joystick getoperatorController() {
		return operatorController;
	}

}
