// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc319.SteamworksBob319.commands.DriveTrain;

import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc319.SteamworksBob319.Robot;

/**
 *
 */
public class SetDrivetrainSpeedLimits extends Command {
	private double forwardSpeedLimit = 0;
	private double backwardSpeedLimit = 0;
	
	public SetDrivetrainSpeedLimits(double forwardLimit, double backwardLimit) {
		forwardSpeedLimit = forwardLimit;
		backwardSpeedLimit = backwardLimit;
		//requires(Robot.driveTrain);

	}

	// Called just before this Command runs the first time
	protected void initialize() {
		Robot.driveTrain.setMaximumForwardSpeed(forwardSpeedLimit);
		Robot.driveTrain.setMaximumBackwardSpeed(backwardSpeedLimit);
	}

	// Called repeatedly when this Command is scheduled to run
	protected void execute() {

	}

	// Make this return true when this Command no longer needs to run execute()
	protected boolean isFinished() {
		return true;
	}

	// Called once after isFinished returns true
	protected void end() {
	}

	// Called when another command which requires one or more of the same
	// subsystems is scheduled to run
	protected void interrupted() {
	}
}
